const list=()=>JSON.parse(localStorage.getItem('streamflix_list')||'[]');
function saveList(a){localStorage.setItem('streamflix_list',JSON.stringify(a))}
function toast(t){const x=document.getElementById('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)}
function toggleList(id){let a=list();a.includes(id)?a=a.filter(x=>x!==id):a.push(id);saveList(a);toast(a.includes(id)?'Added to My List':'Removed from My List');if(typeof renderHome==='function')renderHome(window.__catalogView||MOVIES)}
function card(m){return `<article class="card" onclick="location.href='movie.html?id=${m.id}'"><div class="poster" style="background-image:url('${m.thumb}')"><span class="badge">${m.match}%</span><div class="poster-text"><span class="small">${m.category.toUpperCase()}</span><strong>${m.title}</strong></div><div class="card-info"><button class="circle" onclick="event.stopPropagation();toggleList(${m.id})">${list().includes(m.id)?'✓':'+'}</button></div></div></article>`}
function section(title,arr){return arr.length?`<section class="section"><div class="section-head"><h2>${title}</h2><span class="section-count">${arr.length}</span></div><div class="row">${arr.map(card).join('')}</div></section>`:''}
function renderHome(data=MOVIES){window.__catalogView=data;const groups=[...new Map(MOVIES.map(m=>[m.category,m.category])).keys()];let out='';if(data===MOVIES){out+=section('Trending now',MOVIES.slice(0,10));groups.forEach(g=>out+=section(g,MOVIES.filter(m=>m.category===g)));}else{out+=section('Search / filtered results',data)}document.getElementById('content').innerHTML=out||'<div class="empty">No movies found.</div>';renderHeaderAvatar?.();renderAccountMenu?.()}
function searchMovies(q){q=q.trim().toLowerCase();renderHome(q?MOVIES.filter(m=>m.title.toLowerCase().includes(q)||m.category.toLowerCase().includes(q)||m.genres.some(g=>g.toLowerCase().includes(q))):MOVIES)}
function filterGenre(g){if(g==='Series'){renderHome(MOVIES.filter((m,i)=>i%5===0));return}if(g==='Movies'){renderHome(MOVIES);return}renderHome(MOVIES.filter(m=>m.category.toLowerCase().includes(g.toLowerCase())||m.genres.some(x=>x.toLowerCase()===g.toLowerCase())||m.genre?.toLowerCase()===g.toLowerCase()))}
function showMyList(){renderHome(MOVIES.filter(m=>list().includes(m.id)));}
window.addEventListener('scroll',()=>document.getElementById('topbar')?.classList.toggle('scrolled',scrollY>30));
